### DISCUSSION TITLE
BTsink stereo conversion with ESPHome control, ota

### DISCUSSION THREAD

**Discussion by DAONEW** [pschatzmann/ESP32-A2DP#358] [Show and tell]
Thanks @pschatzmann for the great libraries.

After the inspirational video by [Andreas](https://www.youtube.com/watch?v=a936wNgtcRA) I tried to use your libraries for a BT conversion of my old Stereo. I wanted an easy BT sink controlled via Home Assistant. An external DAC (PCM5102) is used.

Here is my current working setup using ESPHome ota updates. The esp32 is also controlling the stereo via IR commands (left out in the YAML here). 
It's a very crude solution. The esp simply waits for a HA command to turn on the BT sink. If the command to disable BT comes in, the esp restarts into the waiting state.

I wanted to enhance this setup to have a second operating state where the esp is simply streaming web radio or is used as audio output for HA. When I tried this using the audio tools library, I got only one state working at a time. The switching (also by restarting) never worked. When I try this again, I might open an issue there, if you allow :).

Maybe this is useful to some. I would be grateful for any input/suggestions.

YAML: 
````
esphome:
  name: esp32-audio
  platform: ESP32
  board: nodemcu-32s
  includes:
    - advanced_bt_component.h
  libraries:
    - uFire BluetoothA2DPSink=https://github.com/pschatzmann/ESP32-A2DP

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch: # BlueTooth
  - platform: template
    name: "Kitchen Enable Bluetooth"
    id: blink_enable
    optimistic: true
#    restore_state: true

custom_component: # BlueTooth
- lambda: |-
    auto myComponent = new Advanced_bt_Component(id(blink_enable));
    return {myComponent};
````

advanced_bt_Component.h
````
#include "esphome.h"
#include "BluetoothA2DPSink.h"

class Advanced_bt_Component : public Component
{
public:
    BluetoothA2DPSink a2dp_sink;

    Advanced_bt_Component(esphome::template_::TemplateSwitch *&_enable){
        _enable->add_on_state_callback([this](bool newState)
        { 
            if (newState){
                i2s_pin_config_t my_pin_config = {
                    .bck_io_num = 14,
                    .ws_io_num = 15,
                    .data_out_num = 22,
                    .data_in_num = I2S_PIN_NO_CHANGE};
                a2dp_sink.set_pin_config(my_pin_config);
                a2dp_sink.start("Kitchen Radio");
            }
            else
                a2dp_sink.end(true);
        });
    }

    void setup() override {
    }

    void loop() override {
    }
};
````
